benchmark_id: benchmark_gpt-oss-120b
fleet_id: 'fleet_ubix'
models: ["gpt-oss-120b"]
research_space: 'space_1'
enable_logfire: false
runs: 5
experiments:
  exp1:
    experiment_type: zero_shot
    num_records: 1