benchmark_id: benchmark_kimi-k2-0905
fleet_id: 'fleet_ubix'
models: ["kimi-k2-0905"]
research_space: 'space_1'
enable_logfire: false
runs: 5
experiments:
  exp1:
    experiment_type: zero_shot
    num_records: 1